packages:
  - apps/*
  - packages/*
  - ecosystems/*
  - tooling/*
onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  esbuild: true
  sharp: true
storeDir: .pnpm-home/store
verifyDepsBeforeRun: false
