import type { SurfaceProps } from './surfaces/shared';
import { EditorSurface } from './surfaces/EditorSurface';
import { PreviewSurface } from './surfaces/PreviewSurface';
import { PhotosSurface } from './surfaces/PhotosSurface';
import { CalculatorSurface } from './surfaces/CalculatorSurface';
import { CalendarSurface } from './surfaces/CalendarSurface';
import { MailSurface } from './surfaces/MailSurface';
import { MessagesSurface } from './surfaces/MessagesSurface';
import { CallsSurface } from './surfaces/CallsSurface';
import { MediaSurface } from './surfaces/MediaSurface';
import { MapsSurface } from './surfaces/MapsSurface';
import { TasksSurface } from './surfaces/TasksSurface';
import { CanvasSurface } from './surfaces/CanvasSurface';
import { DocumentsSurface } from './surfaces/DocumentsSurface';
import { LibrarySurface } from './surfaces/LibrarySurface';
import { VaultSurface } from './surfaces/VaultSurface';
import { DatabaseSurface } from './surfaces/DatabaseSurface';
import { BlenderSurface } from './surfaces/BlenderSurface';
import { FallbackSurface } from './surfaces/FallbackSurface';

export function AppSpecificSurface({ manifest, computer }: SurfaceProps) {
  if (['textedit', 'notepad', 'gedit'].includes(manifest.id)) return <EditorSurface manifest={manifest} computer={computer}/>;
  if (['preview', 'document-viewer'].includes(manifest.id)) return <PreviewSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'photos') return <PhotosSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'calculator') return <CalculatorSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'calendar') return <CalendarSurface manifest={manifest} computer={computer}/>;
  if (['mail', 'outlook'].includes(manifest.id)) return <MailSurface manifest={manifest} computer={computer}/>;
  if (['messages', 'discord'].includes(manifest.id)) return <MessagesSurface manifest={manifest} computer={computer}/>;
  if (['facetime', 'zoom'].includes(manifest.id)) return <CallsSurface manifest={manifest} computer={computer}/>;
  if (['music', 'rhythmbox', 'spotify', 'vlc', 'audacity'].includes(manifest.id)) return <MediaSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'maps') return <MapsSurface manifest={manifest} computer={computer}/>;
  if (['reminders', 'linear'].includes(manifest.id)) return <TasksSurface manifest={manifest} computer={computer}/>;
  if (['paint', 'gimp', 'snipping-tool'].includes(manifest.id)) return <CanvasSurface manifest={manifest} computer={computer}/>;
  if (['notion', 'obsidian', 'libreoffice'].includes(manifest.id)) return <DocumentsSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'steam') return <LibrarySurface manifest={manifest} computer={computer}/>;
  if (['bitwarden', 'onepassword'].includes(manifest.id)) return <VaultSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'dbeaver') return <DatabaseSurface manifest={manifest} computer={computer}/>;
  if (manifest.id === 'blender') return <BlenderSurface manifest={manifest} computer={computer}/>;
  return <FallbackSurface manifest={manifest} computer={computer}/>;
}
