import { useState } from 'react';
import { Layers3, Play, SlidersHorizontal, WandSparkles } from 'lucide-react';
import { Brand, runOperation, type SurfaceProps } from './shared';

export function BlenderSurface({ manifest, computer }: SurfaceProps) {
  const [mode, setMode] = useState('Object Mode');
  const [propTab, setPropTab] = useState(0);
  const [selectedObject, setSelectedObject] = useState('DesktopShell');
  const changeMode = async (next: string) => { if (await runOperation(manifest, computer, 'edit-properties', { property: 'mode', value: next })) setMode(next); };
  const selectObject = async (item: string) => { if (await runOperation(manifest, computer, 'select', { object: item })) setSelectedObject(item); };
  return <div className="blender-app surface-blender"><header><Brand manifest={manifest}/><span>File  Edit  Render  Window  Help</span><b>Layout</b><span>Modeling</span><span>Shading</span></header><aside><h5>SCENE COLLECTION</h5>{['Camera','Key Light','DesktopShell','WindowGroup','EvidenceGrid'].map((item) => <button className={selectedObject === item ? 'active' : ''} onClick={() => void selectObject(item)} key={item}><i/>{item}</button>)}</aside><main><div className="viewport-toolbar"><select value={mode} onChange={(event) => void changeMode(event.target.value)}><option>Object Mode</option><option>Edit Mode</option><option>Sculpt Mode</option></select><button onClick={() => void runOperation(manifest, computer, 'transform', { space: 'global' })}>Global</button><span/><button>●</button><button>◐</button><button>◒</button></div><div className="viewport"><div className="axis"><i className="x">X</i><i className="y">Y</i><i className="z">Z</i></div><div className="grid-floor"/><div className="blender-cube"><i className="front"/><i className="side"/><i className="top"/></div><span className="object-label">{selectedObject}</span></div><div className="timeline-bar"><button>⏮</button><button onClick={() => void runOperation(manifest, computer, 'edit-properties', { property: 'timeline-playing', value: true })}><Play/></button><span>1</span><input type="range" defaultValue="1" onChange={(event) => void runOperation(manifest, computer, 'edit-properties', { property: 'frame', value: Number(event.target.value) })}/><span>250</span></div></main><aside className="properties"><nav>{[<SlidersHorizontal/>, <WandSparkles/>, <Layers3/>].map((icon, index) => <button key={index} className={propTab === index ? 'active' : ''} onClick={() => setPropTab(index)}>{icon}</button>)}</nav>{propTab === 0 && <><h4>Transform · {selectedObject}</h4>{['Location','Rotation','Scale'].map((item, index) => <p key={item}><b>{item}</b><span>X {index ? '1.000' : '0 m'}</span><span>Y {index ? '1.000' : '0 m'}</span><span>Z {index ? '1.000' : '0 m'}</span></p>)}</>}{propTab === 1 && <><h4>Modifiers</h4><p><b>Subdivision</b><span>Levels 2</span></p><p><b>Bevel</b><span>Width 0.02</span></p></>}{propTab === 2 && <><h4>Object Data</h4><p><b>Vertices</b><span>8</span></p><p><b>Faces</b><span>6</span></p></>}</aside></div>;
}
