import { useState } from 'react';
import { Crop, Image, MousePointer2, PenTool, Plus } from 'lucide-react';
import { Brand, runOperation, type SurfaceProps } from './shared';

export function CanvasSurface({ manifest, computer }: SurfaceProps) {
  const [tool, setTool] = useState(manifest.id === 'snipping-tool' ? 'Rectangle' : 'Brush');
  const [marks, setMarks] = useState<Array<{ x: number; y: number }>>([]);
  const [snipMode, setSnipMode] = useState('Rectangle');
  const [delay, setDelay] = useState('No delay');
  const [annotateTool, setAnnotateTool] = useState('');
  const [copied, setCopied] = useState(false);
  const [captured, setCaptured] = useState(true);
  if (manifest.id === 'snipping-tool') return <div className="capture-app surface-snipping-tool"><header><Brand manifest={manifest}/><button className="primary" onClick={() => void runOperation(manifest, computer, 'capture-region', { x: 80, y: 60, width: 1240, height: 760, mode: snipMode, delay }).then(() => { setCaptured(true); setCopied(false); })}>+ New</button><select value={snipMode} onChange={(event) => setSnipMode(event.target.value)}>{['Rectangle','Window','Full-screen','Freeform'].map((mode) => <option key={mode}>{mode}</option>)}</select><select value={delay} onChange={(event) => setDelay(event.target.value)}>{['No delay','3s delay','5s delay','10s delay'].map((option) => <option key={option}>{option}</option>)}</select></header><main><div className="capture-preview">{captured ? <div className="capture-selection"><i/><i/><i/><i/><span>1240 × 760 · {snipMode}</span></div> : <span style={{ opacity: 0.5 }}>No capture — press + New</span>}</div><footer><button className={annotateTool === 'crop' ? 'active' : ''} onClick={() => { setAnnotateTool('crop'); void runOperation(manifest, computer, 'annotate', { tool: 'crop' }); }}><Crop/></button><button className={annotateTool === 'pen' ? 'active' : ''} onClick={() => { setAnnotateTool('pen'); void runOperation(manifest, computer, 'annotate', { tool: 'pen' }); }}><PenTool/></button><button className={annotateTool === 'highlighter' ? 'active' : ''} onClick={() => { setAnnotateTool('highlighter'); void runOperation(manifest, computer, 'annotate', { tool: 'highlighter' }); }}>Highlighter</button><button className={annotateTool === 'erase' ? 'active' : ''} onClick={() => { setAnnotateTool('erase'); void runOperation(manifest, computer, 'annotate', { tool: 'erase' }); }}>Erase</button><span/><button onClick={() => { setCopied(true); void runOperation(manifest, computer, 'copy', { target: 'clipboard' }); }}>{copied ? 'Copied' : 'Copy'}</button><button onClick={() => void runOperation(manifest, computer, 'save', { path: `${computer.spec.os === 'windows' ? '/C/Users/agent' : '/home/agent'}/Pictures/Screenshot.png` })}>Save</button></footer></main></div>;
  const gimp = manifest.id === 'gimp';
  return <div className={`canvas-app surface-${manifest.id} ${gimp ? 'gimp' : 'paint'}`}><header><Brand manifest={manifest}/><span>{gimp ? 'File  Edit  Select  View  Image  Layer  Colors  Tools  Filters' : 'File  Home  View'}</span><button onClick={() => void runOperation(manifest, computer, 'save', { path: `${computer.spec.os === 'windows' ? '/C/Users/agent' : '/home/agent'}/Documents/interaction-evidence.seed-canvas`, content: JSON.stringify({ marks }) })}>Save</button></header><div className="canvas-toolbar">{['Select','Brush','Fill','Text','Shapes'].map((item) => <button className={tool === item ? 'active' : ''} onClick={() => setTool(item)} key={item}>{item === 'Select' ? <MousePointer2/> : item === 'Brush' ? <PenTool/> : item === 'Fill' ? '▰' : item[0]}<span>{item}</span></button>)}<label>Size<input type="range" defaultValue="38"/></label><div className="palette">{['#111827','#ef4444','#f59e0b','#10b981','#3b82f6','#8b5cf6'].map((color) => <button key={color} style={{ background: color }}/>)}</div></div><main>{gimp && <aside><h5>TOOL OPTIONS</h5><p>Opacity <b>100</b></p><p>Dynamics <b>Pressure</b></p><p>Spacing <b>10</b></p></aside>}<div className="canvas-stage"><div className="paint-canvas" onClick={(event) => { const bounds = event.currentTarget.getBoundingClientRect(); const mark = { x: event.clientX - bounds.left, y: event.clientY - bounds.top }; void runOperation(manifest, computer, 'draw', { tool, ...mark }).then((ok) => { if (ok) setMarks((items) => [...items, mark]); }); }}><h2>Seed OS</h2><p>interaction evidence</p>{marks.map((mark, index) => <i key={index} style={{ left: mark.x, top: mark.y }}/>)}</div></div>{gimp && <aside className="layers"><h5>LAYERS</h5><button className="active"><Image/> evidence-overlay</button><button><Image/> desktop-capture</button><button onClick={() => void runOperation(manifest, computer, 'new-document', { layer: 'Untitled layer' })}><Plus/> New layer</button></aside>}</main><footer>{tool} · 1600 × 900 · {marks.length + (gimp ? 2 : 1)} layers</footer></div>;
}
