import { useState } from 'react';
import { FileText, Plus, Search, Sparkles } from 'lucide-react';
import { Brand, runOperation, type SurfaceProps } from './shared';

export function DocumentsSurface({ manifest, computer }: SurfaceProps) {
  const [page, setPage] = useState(0);
  const [shared, setShared] = useState(false);
  if (manifest.id === 'libreoffice') return <div className="office-app surface-libreoffice"><header><Brand manifest={manifest}/><span>File  Edit  View  Insert  Format  Styles  Table  Form  Tools  Help</span></header><div className="office-toolbar"><button>↶</button><button>↷</button><select><option>Heading 1</option></select><select><option>Liberation Sans</option></select><select><option>24 pt</option></select><button><b>B</b></button><button><i>I</i></button><button>≡</button></div><main><article contentEditable suppressContentEditableWarning onBlur={(event) => void runOperation(manifest, computer, 'save', { path: '/home/agent/Documents/seed-computer-ecosystem.odt.seed', content: event.currentTarget.innerText })}><h1>Seed computer ecosystem</h1><p><b>Research environment specification</b></p><p>This document records the observable contract between the desktop UI, virtual filesystem, process table, application services and network trace.</p><h2>Acceptance criteria</h2><ul><li>Application actions cause inspectable state transitions.</li><li>Service boundaries match real product architecture.</li><li>Evidence can be replayed from trajectory events.</li></ul></article></main><footer>Page 1 of 3 <span>English (USA)</span><span>312 words</span><span>100%</span></footer></div>;
  const obsidian = manifest.id === 'obsidian';
  const pages = ['Simulator architecture', 'Application services', 'Evidence protocol', 'Research questions'];
  return <div className={`documents-app surface-${manifest.id} ${obsidian ? 'obsidian' : 'notion'}`}><aside><Brand manifest={manifest}/><label><Search/><input placeholder="Search"/></label><button onClick={() => void runOperation(manifest, computer, 'new-document', { title: 'Untitled' })}><Plus/> New page</button><h5>{obsidian ? 'SEED-VAULT' : 'WORKSPACE'}</h5>{pages.map((name, index) => <button className={page === index ? 'active' : ''} onClick={() => void runOperation(manifest, computer, 'open', { page: name }).then((ok) => ok && setPage(index))} key={name}><FileText/>{name}</button>)}</aside><section><header><span>Research / {pages[page]}</span><button className={shared ? 'active' : ''} onClick={() => { setShared(true); void runOperation(manifest, computer, 'share', { page: pages[page] }); setTimeout(() => setShared(false), 1200); }}>{shared ? 'Link copied' : 'Share'}</button><button>•••</button></header><article contentEditable suppressContentEditableWarning onBlur={(event) => void runOperation(manifest, computer, 'save', { path: `${computer.spec.os === 'windows' ? '/C/Users/agent' : '/home/agent'}/Documents/${pages[page]}.md`, content: event.currentTarget.innerText })}><div className="page-icon">{obsidian ? '◇' : '🖥️'}</div><h1>{pages[page]}</h1><p className="lead">A working note grounded in the currently mounted simulator workspace.</p><h2>{page === 0 ? 'One state, many projections' : page === 1 ? 'Independent service planes' : page === 2 ? 'Trajectory-backed proof' : 'Open questions'}</h2><p>The GUI is useful evidence only when its contents are causally linked to the same model exposed through shell commands and APIs.</p><div className="document-callout"><Sparkles/><span>Next: verify this claim against a fresh interaction trace.</span></div><label><input type="checkbox" defaultChecked onChange={(event) => void runOperation(manifest, computer, 'edit', { field: 'vfs-persists', checked: event.target.checked })}/> VFS state persists after reload</label><label><input type="checkbox" onChange={(event) => void runOperation(manifest, computer, 'edit', { field: 'replay-window-state', checked: event.target.checked })}/> replay reproduces window state</label></article>{obsidian && <aside className="backlinks"><h5>BACKLINKS</h5>{[0, 1].map((index) => <button key={index} className={page === index ? 'active' : ''} onClick={() => void runOperation(manifest, computer, 'open', { page: pages[index] }).then((ok) => ok && setPage(index))}>{pages[index]}</button>)}<h5>GRAPH</h5><div className="mini-graph"><i/><i/><i/><i/></div></aside>}</section></div>;
}
